### ISSUE TITLE
InfluxDB 2 is not supported

### ISSUE THREAD

**Issue by orangecoding** [emilp/homebridge-influxdb-temperature-humidity#1]
Hi,

this plugin is not compatible to InfluxDB 2 due to the old influx client that is being used. Is it planned to upgrade this to support v2 of Influx?

**Comment by emilp** [comment]
Hi!

No, I'm not planning this right now. My Raspbian has still InfluxDB v1.6. Also, I can see that my other Ubuntus and Debian have v1.6.
